import { randomBytes } from 'node:crypto';
import { existsSync, renameSync } from 'node:fs';
import { promises as fsp } from 'node:fs';
import { join } from 'node:path';
import type { SiteInfo } from './profile.js';

// Constants that must not carry over: DB credentials are DDEV's, cache/cron
// are forced off by the harness, path/URL constants point into production, and
// cookie/session constants are scoped to production's domain/siteurl.
const SKIP_CONSTANTS = new Set([
  'DB_NAME', 'DB_USER', 'DB_PASSWORD', 'DB_HOST', 'DB_CHARSET', 'DB_COLLATE',
  'WP_CACHE', 'DISABLE_WP_CRON', 'ABSPATH', 'FERRY_LOCAL_URL',
  'WP_HOME', 'WP_SITEURL', 'WP_CONTENT_DIR', 'WP_CONTENT_URL',
  'WP_PLUGIN_DIR', 'WP_PLUGIN_URL', 'WPMU_PLUGIN_DIR', 'WP_TEMP_DIR',
  'COOKIE_DOMAIN', 'COOKIEHASH',
]);

const SALT_KEYS = [
  'AUTH_KEY', 'SECURE_AUTH_KEY', 'LOGGED_IN_KEY', 'NONCE_KEY',
  'AUTH_SALT', 'SECURE_AUTH_SALT', 'LOGGED_IN_SALT', 'NONCE_SALT',
];

export const DROP_INS = ['object-cache.php', 'advanced-cache.php', 'db.php', 'sunrise.php'];

export function phpScalar(v: unknown): string | null {
  if (v === null) return 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'string') return `'${v.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  return null;
}

/** §2.5 + §4.4: wp-config is regenerated locally; production's never crosses the bridge. */
export function generateWpConfig(info: SiteInfo, localUrl: string): string {
  const lines = [
    '<?php',
    '/* Generated by ferry - local clone configuration. Local artifact, never pushed. */',
    "define('DB_NAME', 'db');",
    "define('DB_USER', 'db');",
    "define('DB_PASSWORD', 'db');",
    "define('DB_HOST', 'db');",
    "define('DB_CHARSET', 'utf8mb4');",
    "define('DB_COLLATE', '');",
    '',
    `$table_prefix = ${phpScalar(info.prefix)};`,
    '',
    '/* Production wp-config constants, carried for parity (base doc §2.5). */',
  ];
  for (const [name, value] of Object.entries(info.constants ?? {})) {
    if (SKIP_CONSTANTS.has(name)) continue;
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) continue;
    if (typeof value === 'string' && value.startsWith('/')) continue; // production filesystem path
    const scalar = phpScalar(value);
    if (scalar === null) continue;
    lines.push(`define('${name}', ${scalar});`);
  }
  lines.push(
    '',
    '/* Ferry local overrides. */',
    "define('WP_CACHE', false);",
    "define('DISABLE_WP_CRON', true);",
    `define('FERRY_LOCAL_URL', ${phpScalar(localUrl)});`,
    '',
  );
  for (const key of SALT_KEYS) {
    lines.push(`define('${key}', ${phpScalar(randomBytes(32).toString('base64'))});`);
  }
  lines.push(
    '',
    "if (!defined('ABSPATH')) { define('ABSPATH', __DIR__ . '/'); }",
    "require_once ABSPATH . 'wp-settings.php';",
    '',
  );
  return lines.join('\n');
}

/**
 * §2.6 runtime URL mapping + §2.7 containment harness. Classic closures only:
 * this file runs on the clone's PHP, which mirrors production (can be 7.0-era).
 */
export function generateMuPlugin(): string {
  return `<?php
/* Ferry local overlay - generated. Runtime URL mapping + containment harness. */
add_filter('pre_option_siteurl', function () { return FERRY_LOCAL_URL; });
add_filter('pre_option_home', function () { return FERRY_LOCAL_URL; });
add_filter('pre_wp_mail', '__return_false');
add_filter('pre_http_request', function ($pre, $args, $url) {
    error_log('[ferry-harness] blocked outbound HTTP: ' . $url);
    return new WP_Error('ferry_blocked', 'ferry harness: outbound HTTP is blocked in the clone (' . $url . ')');
}, 1, 3);
`;
}

/**
 * §2.8: solve uploads on the HTTP level - local if present, 302 to production if not.
 * `^~` makes this a preferential prefix match: when it matches, nginx skips regex
 * locations entirely. Without it, DDEV's `location ~* \.(png|jpg|...)$` static-media
 * handler matches an uploaded image first and 404s it before this fallback runs.
 */
export function generateNginxFallback(prodOrigin: string): string {
  return `location ^~ /wp-content/uploads/ {
    try_files $uri @ferry_origin;
}
location @ferry_origin {
    return 302 ${prodOrigin}$request_uri;
}
`;
}

export function generateHtaccessFallback(prodOrigin: string): string {
  return `# BEGIN ferry-uploads-fallback
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^wp-content/uploads/(.*)$ ${prodOrigin}/wp-content/uploads/$1 [R=302,L]
</IfModule>
# END ferry-uploads-fallback
`;
}

/** Phase 1 (before ddev start): config files DDEV must see at boot. */
export async function applyOverlay(docroot: string, info: SiteInfo, localUrl: string): Promise<void> {
  await fsp.writeFile(join(docroot, 'wp-config.php'), generateWpConfig(info, localUrl));
  await fsp.mkdir(join(docroot, 'wp-content', 'mu-plugins'), { recursive: true });
  await fsp.writeFile(join(docroot, 'wp-content', 'mu-plugins', 'ferry-overlay.php'), generateMuPlugin());
  await fsp.mkdir(join(docroot, '.ddev', 'nginx'), { recursive: true });
  await fsp.writeFile(
    join(docroot, '.ddev', 'nginx', 'ferry-uploads.conf'),
    generateNginxFallback(new URL(info.siteurl).origin),
  );
}

/** §2.6: drop-ins fatal locally (no Redis, wrong paths) - the classic white-screen cause. */
export function neutralizeDropIns(docroot: string): string[] {
  const renamed: string[] = [];
  for (const dropIn of DROP_INS) {
    const path = join(docroot, 'wp-content', dropIn);
    const disabled = `${path}.ferry-disabled`;
    if (existsSync(path) && !existsSync(disabled)) {
      renameSync(path, disabled);
      renamed.push(dropIn);
    }
  }
  return renamed;
}

/** Phase 2 (after file transfer): work on files that arrive with the pull. */
export async function finalizeClone(docroot: string, info: SiteInfo): Promise<string[]> {
  const renamed = neutralizeDropIns(docroot);
  if (info.server === 'apache') {
    const htaccessPath = join(docroot, '.htaccess');
    const existing = existsSync(htaccessPath) ? await fsp.readFile(htaccessPath, 'utf8') : '';
    if (!existing.includes('# BEGIN ferry-uploads-fallback')) {
      await fsp.writeFile(
        htaccessPath,
        generateHtaccessFallback(new URL(info.siteurl).origin) + existing,
      );
    }
  }
  return renamed;
}
