[supervisord]
nodaemon=true

[program:mariadb]
command=/usr/sbin/mariadbd --user=mysql
priority=1
autorestart=true

[program:apache]
command=apache2-foreground
priority=2
autorestart=true

[program:sited]
command=node --import tsx /opt/ferry/ferry-sited/src/main.ts
directory=/opt/ferry
environment=SITED_DOCROOT="/data/www",SITED_HOST="::"
priority=3
autorestart=true
